// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Apartment
    {
        public Apartment()
        {
            Users = new HashSet<User>();
        }

        public int Id { get; set; }
        public int IdCondominium { get; set; }
        public string Number { get; set; }
        public int Type { get; set; }
        public string Parking { get; set; }
        public string ContactName { get; set; }
        public bool Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }

        public virtual Condominium IdCondominiumNavigation { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}