// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Appointment
    {
        public Appointment()
        {
            AppointmentWorkOrderServices = new HashSet<AppointmentWorkOrderService>();
            DocumentAppointments = new HashSet<DocumentAppointment>();
            RelAppointmentHousingLists = new HashSet<RelAppointmentHousingList>();
            RelAppointmentSchoolingLists = new HashSet<RelAppointmentSchoolingList>();
        }

        public int Id { get; set; }
        public int? ServiceRecordId { get; set; }
        public DateTime Date { get; set; }
        public DateTime? StartTime { get; set; }
        public string StartTimeMeridian { get; set; }
        public DateTime? EndTime { get; set; }
        public string EndTimeMeridian { get; set; }
        public string Description { get; set; }
        public string CommentCancel { get; set; }
        public int? Status { get; set; }
        public int? Report { get; set; }
        public bool? Start { get; set; }
        public bool? Ended { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int To { get; set; }
        public int From { get; set; }

        public virtual User FromNavigation { get; set; }
        public virtual ReportDay ReportNavigation { get; set; }
        public virtual ServiceRecord ServiceRecord { get; set; }
        public virtual CatStatusAppointment StatusNavigation { get; set; }
        public virtual User ToNavigation { get; set; }
        public virtual ICollection<AppointmentWorkOrderService> AppointmentWorkOrderServices { get; set; }
        public virtual ICollection<DocumentAppointment> DocumentAppointments { get; set; }
        public virtual ICollection<RelAppointmentHousingList> RelAppointmentHousingLists { get; set; }
        public virtual ICollection<RelAppointmentSchoolingList> RelAppointmentSchoolingLists { get; set; }
    }
}