// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class AssignedServiceRelocation
    {
        public int Id { get; set; }
        public int? StandaloneServiceId { get; set; }
        public int? PackageServiceId { get; set; }
        public int? RelocationSupplierPartnerId { get; set; }

        public virtual PackageService PackageService { get; set; }
        public virtual RelocationSupplierPartner RelocationSupplierPartner { get; set; }
        public virtual StandaloneService StandaloneService { get; set; }
    }
}