// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatPaymetMethod
    {
        public CatPaymetMethod()
        {
            AirportTransportationServices = new HashSet<AirportTransportationService>();
            LandLordBankDetails = new HashSet<LandLordBankDetail>();
            RentalFurnitureCoordinations = new HashSet<RentalFurnitureCoordination>();
        }

        public int Id { get; set; }
        public string PaymentMethods { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<AirportTransportationService> AirportTransportationServices { get; set; }
        public virtual ICollection<LandLordBankDetail> LandLordBankDetails { get; set; }
        public virtual ICollection<RentalFurnitureCoordination> RentalFurnitureCoordinations { get; set; }
    }
}