// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatRelationshipContact
    {
        public CatRelationshipContact()
        {
            EmergencyContacts = new HashSet<EmergencyContact>();
        }

        public int Id { get; set; }
        public string Relationship { get; set; }
        public bool? Status { get; set; }

        public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; }
    }
}