// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatStatusAppointment
    {
        public CatStatusAppointment()
        {
            Appointments = new HashSet<Appointment>();
        }

        public int Id { get; set; }
        public string Status { get; set; }

        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}