// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatState
    {
        public CatState()
        {
            CatCities = new HashSet<CatCity>();
        }

        public int Id { get; set; }
        public string State { get; set; }
        public int IdCountry { get; set; }

        public virtual CatCountry IdCountryNavigation { get; set; }
        public virtual ICollection<CatCity> CatCities { get; set; }
    }
}