// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class City
    {
        public City()
        {
            AssigneeInformations = new HashSet<AssigneeInformation>();
            OfficeContacts = new HashSet<OfficeContact>();
            OfficeInformations = new HashSet<OfficeInformation>();
        }

        public int Id { get; set; }
        public int IdState { get; set; }
        public string Name { get; set; }

        public virtual State IdStateNavigation { get; set; }
        public virtual ICollection<AssigneeInformation> AssigneeInformations { get; set; }
        public virtual ICollection<OfficeContact> OfficeContacts { get; set; }
        public virtual ICollection<OfficeInformation> OfficeInformations { get; set; }
    }
}