// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Condominium
    {
        public Condominium()
        {
            Apartments = new HashSet<Apartment>();
            RoleCondominia = new HashSet<RoleCondominium>();
        }

        public int Id { get; set; }
        public string Condominium1 { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string OutdoorNumber { get; set; }
        public string InsideNumber { get; set; }
        public string PostalCode { get; set; }
        public int IdLocation { get; set; }
        public int IdState { get; set; }
        public int IdMunicipality { get; set; }
        public bool Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }

        public virtual ICollection<Apartment> Apartments { get; set; }
        public virtual ICollection<RoleCondominium> RoleCondominia { get; set; }
    }
}