// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ContractDetail
    {
        public ContractDetail()
        {
            PropertyExpenses = new HashSet<PropertyExpense>();
        }

        public int ContractDetailId { get; set; }
        public DateTime? LeaseStartDate { get; set; }
        public DateTime? LeaseEndDate { get; set; }
        public string PaymentsDue { get; set; }
        public decimal? ListRentPrice { get; set; }
        public int? Currency { get; set; }
        public decimal? FinalRentPrice { get; set; }
        public int? CurrencyFinal { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string Recurrence { get; set; }
        public int IdContract { get; set; }
        public int? IdServiceDetail { get; set; }
        public bool? Visible { get; set; }
        public decimal? Rentcostsaving { get; set; }
        public int? Leasesignatories { get; set; }
        public string Namesinatore { get; set; }
        public string Emailsinatore { get; set; }
        public string Telsinatore { get; set; }

        public virtual HousingList ContractDetailNavigation { get; set; }
        public virtual CatCurrency CurrencyFinalNavigation { get; set; }
        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual ICollection<PropertyExpense> PropertyExpenses { get; set; }
    }
}