// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Country
    {
        public Country()
        {
            AssigneeInformations = new HashSet<AssigneeInformation>();
            OfficeInformations = new HashSet<OfficeInformation>();
            States = new HashSet<State>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<AssigneeInformation> AssigneeInformations { get; set; }
        public virtual ICollection<OfficeInformation> OfficeInformations { get; set; }
        public virtual ICollection<State> States { get; set; }
    }
}