// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DependentInformationLanguage
    {
        public int Id { get; set; }
        public int LanguageId { get; set; }
        public int DependentInformationId { get; set; }

        public virtual DependentInformation DependentInformation { get; set; }
        public virtual CatLanguage Language { get; set; }
    }
}