// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class GroupCostSaving
    {
        public GroupCostSaving()
        {
            CostSavingHomes = new HashSet<CostSavingHome>();
        }

        public int Id { get; set; }
        public bool? Visible { get; set; }
        public int? IdServiceDetail { get; set; }
        public int? HousingListId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string ServiceNumber { get; set; }
        public string ServiceTypeText { get; set; }
        public string WorkOrderText { get; set; }

        public virtual HousingList HousingList { get; set; }
        public virtual ICollection<CostSavingHome> CostSavingHomes { get; set; }
    }
}