// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class HousingList
    {
        public HousingList()
        {
            AmenitiesHousingLists = new HashSet<AmenitiesHousingList>();
            CommentHousings = new HashSet<CommentHousing>();
            ContractDetails = new HashSet<ContractDetail>();
            DepartureDetailsHomes = new HashSet<DepartureDetailsHome>();
            Departures = new HashSet<Departure>();
            DocumentHousings = new HashSet<DocumentHousing>();
            GroupCostSavings = new HashSet<GroupCostSaving>();
            GroupPaymnetsHousings = new HashSet<GroupPaymnetsHousing>();
            HomeSales = new HashSet<HomeSale>();
            HousingReports = new HashSet<HousingReport>();
            HousingStatusHistories = new HashSet<HousingStatusHistory>();
            Inspections = new HashSet<Inspection>();
            LandlordHeaderDetailsHomes = new HashSet<LandlordHeaderDetailsHome>();
            PropertyReports = new HashSet<PropertyReport>();
            RelAppointmentHousingLists = new HashSet<RelAppointmentHousingList>();
            RenewalDetailHomes = new HashSet<RenewalDetailHome>();
            Repairs = new HashSet<Repair>();
            TenancyManagements = new HashSet<TenancyManagement>();
        }

        public int Id { get; set; }
        public int? WorkOrder { get; set; }
        public int? Service { get; set; }
        public int? ServiceType { get; set; }
        public int? PropertyNo { get; set; }
        public bool? Sample { get; set; }
        public int? SupplierPartner { get; set; }
        public int? Supplier { get; set; }
        public DateTime? VisitDate { get; set; }
        public int? HousingStatus { get; set; }
        public int? PropertyType { get; set; }
        public string Address { get; set; }
        public int? Zip { get; set; }
        public string WebSite { get; set; }
        public int? Bedrooms { get; set; }
        public int? Bathrooms { get; set; }
        public int? ParkingSpaces { get; set; }
        public decimal? Price { get; set; }
        public int? Currency { get; set; }
        public string AdditionalComments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? IdServiceDetail { get; set; }
        public string Othersupplier { get; set; }
        public string Suppliertelephone { get; set; }
        public string Supplieremail { get; set; }
        public int? Shared { get; set; }
        public string Neighborhood { get; set; }
        public string VisitTime { get; set; }
        public bool? Wassended { get; set; }

        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual CatStatusHousing HousingStatusNavigation { get; set; }
        public virtual CatPropertyTypeHousing PropertyTypeNavigation { get; set; }
        public virtual AdministrativeContactsService SupplierNavigation { get; set; }
        public virtual SupplierPartnerProfileService SupplierPartnerNavigation { get; set; }
        public virtual WorkOrder WorkOrderNavigation { get; set; }
        public virtual ICollection<AmenitiesHousingList> AmenitiesHousingLists { get; set; }
        public virtual ICollection<CommentHousing> CommentHousings { get; set; }
        public virtual ICollection<ContractDetail> ContractDetails { get; set; }
        public virtual ICollection<DepartureDetailsHome> DepartureDetailsHomes { get; set; }
        public virtual ICollection<Departure> Departures { get; set; }
        public virtual ICollection<DocumentHousing> DocumentHousings { get; set; }
        public virtual ICollection<GroupCostSaving> GroupCostSavings { get; set; }
        public virtual ICollection<GroupPaymnetsHousing> GroupPaymnetsHousings { get; set; }
        public virtual ICollection<HomeSale> HomeSales { get; set; }
        public virtual ICollection<HousingReport> HousingReports { get; set; }
        public virtual ICollection<HousingStatusHistory> HousingStatusHistories { get; set; }
        public virtual ICollection<Inspection> Inspections { get; set; }
        public virtual ICollection<LandlordHeaderDetailsHome> LandlordHeaderDetailsHomes { get; set; }
        public virtual ICollection<PropertyReport> PropertyReports { get; set; }
        public virtual ICollection<RelAppointmentHousingList> RelAppointmentHousingLists { get; set; }
        public virtual ICollection<RenewalDetailHome> RenewalDetailHomes { get; set; }
        public virtual ICollection<Repair> Repairs { get; set; }
        public virtual ICollection<TenancyManagement> TenancyManagements { get; set; }
    }
}