// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Inspection
    {
        public Inspection()
        {
            AttendeeInspecs = new HashSet<AttendeeInspec>();
            PhotosInspecs = new HashSet<PhotosInspec>();
        }

        public int Id { get; set; }
        public int? HousingList { get; set; }
        public DateTime InitialInspectionDate { get; set; }
        public DateTime? FinalInspectionDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? IdServiceDetail { get; set; }
        public int? PropertySection { get; set; }
        public string InspecDetails { get; set; }

        public virtual HousingList HousingListNavigation { get; set; }
        public virtual CatPropertySection PropertySectionNavigation { get; set; }
        public virtual ICollection<AttendeeInspec> AttendeeInspecs { get; set; }
        public virtual ICollection<PhotosInspec> PhotosInspecs { get; set; }
    }
}