// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ItemsSectionInventory
    {
        public ItemsSectionInventory()
        {
            SectionInventories = new HashSet<SectionInventory>();
        }

        public int Id { get; set; }
        public string Item { get; set; }
        public int? PropertySection { get; set; }

        public virtual CatPropertySection PropertySectionNavigation { get; set; }
        public virtual ICollection<SectionInventory> SectionInventories { get; set; }
    }
}