// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class KeyTableService
    {
        public KeyTableService()
        {
            KeyReloDetailServices = new HashSet<KeyReloDetailService>();
        }

        public int Id { get; set; }
        public int? StandaloneServiceWorkOrderId { get; set; }
        public int? BundledServicesId { get; set; }
        public int? AssigneId { get; set; }
        public int? DeliveringInId { get; set; }
        public int? CatServiceId { get; set; }
        public int? CatServiceLineId { get; set; }
        public int? IdServiceDetail { get; set; }
        public bool? IsBundled { get; set; }

        public virtual ICollection<KeyReloDetailService> KeyReloDetailServices { get; set; }
    }
}