// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PaymentSchooling
    {
        public int Id { get; set; }
        public int? SchoolingSearchId { get; set; }
        public int? Responsible { get; set; }
        public string Description { get; set; }
        public int? Currency { get; set; }
        public decimal? Amount { get; set; }

        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual CatResponsablePayment ResponsibleNavigation { get; set; }
        public virtual SchoolingSearch SchoolingSearch { get; set; }
    }
}