// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PaymentHousing
    {
        public int Id { get; set; }
        public int? HousingList { get; set; }
        public int? PaymentType { get; set; }
        public int? Responsible { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? Currency { get; set; }
        public decimal? Amount { get; set; }
        public int? IdServiceDetail { get; set; }
        public int? GroupPaymentsHousingId { get; set; }

        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual GroupPaymnetsHousing GroupPaymentsHousing { get; set; }
        public virtual CatPaymentTypeStatus PaymentTypeNavigation { get; set; }
        public virtual CatResponsablePayment ResponsibleNavigation { get; set; }
    }
}