// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class RoleCondominium
    {
        public RoleCondominium()
        {
            Users = new HashSet<User>();
        }

        public int Id { get; set; }
        public int IdRole { get; set; }
        public int IdCondominium { get; set; }

        public virtual Condominium IdCondominiumNavigation { get; set; }
        public virtual Role IdRoleNavigation { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}