// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Role
    {
        public Role()
        {
            RoleCondominia = new HashSet<RoleCondominium>();
        }

        public int Id { get; set; }
        public string Role1 { get; set; }
        public bool Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }

        public virtual ICollection<RoleCondominium> RoleCondominia { get; set; }
    }
}