// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class SchoolingListLanguange
    {
        public int Id { get; set; }
        public int? IdLanguage { get; set; }
        public int? IdSchoolingList { get; set; }

        public virtual CatLanguage IdLanguageNavigation { get; set; }
        public virtual SchoolsList IdSchoolingListNavigation { get; set; }
    }
}