// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class SecurityDeposit
    {
        public SecurityDeposit()
        {
            DepartureDetailsHomes = new HashSet<DepartureDetailsHome>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<DepartureDetailsHome> DepartureDetailsHomes { get; set; }
    }
}