// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ServiceOrder
    {
        public ServiceOrder()
        {
            PackageServices = new HashSet<PackageService>();
            StandaloneServices = new HashSet<StandaloneService>();
        }

        public int Id { get; set; }
        public DateTime? Autho { get; set; }
        public int? ServiceLineId { get; set; }
        public int? ServiceRecordId { get; set; }

        public virtual CatServiceLine ServiceLine { get; set; }
        public virtual ServiceRecord ServiceRecord { get; set; }
        public virtual ICollection<PackageService> PackageServices { get; set; }
        public virtual ICollection<StandaloneService> StandaloneServices { get; set; }
    }
}