// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class StandaloneService
    {
        public StandaloneService()
        {
            AssignedServiceRelocations = new HashSet<AssignedServiceRelocation>();
        }

        public int Id { get; set; }
        public int? DeliveredTo { get; set; }
        public int? DeliveringIn { get; set; }
        public string Location { get; set; }
        public DateTime? Acceptance { get; set; }
        public bool? Coordination { get; set; }
        public int? AuthoTime { get; set; }
        public string ProjectedFee { get; set; }
        public int? ServiceOrderId { get; set; }
        public int? ServiceId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatService Service { get; set; }
        public virtual ServiceOrder ServiceOrder { get; set; }
        public virtual ICollection<AssignedServiceRelocation> AssignedServiceRelocations { get; set; }
    }
}