// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class State
    {
        public State()
        {
            Cities = new HashSet<City>();
            OfficeInformations = new HashSet<OfficeInformation>();
        }

        public int Id { get; set; }
        public int IdCountry { get; set; }
        public string Name { get; set; }

        public virtual Country IdCountryNavigation { get; set; }
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<OfficeInformation> OfficeInformations { get; set; }
    }
}